### ISSUE TITLE
Consider splitting the API into lower-level primitives

### ISSUE THREAD

**Issue by koto** [WICG/sanitizer-api#1]
Existing client-side HTML sanitizers (I'll focus on [DOMPurify](https://github.com/cure53/DOMPurify) and [Closure HTML sanitizer](https://github.com/google/closure-library/tree/master/closure/goog/html/sanitizer) as I know them the most) deal with a couple of tasks to prevent XSS:
 1. Creating an inert HTML document to put the dirty HTML into.
 1. Traversing the DOM safely (using a couple of DOM APIs with some hardening against DOM clobbering).
 1. Applying a "baseline" whitelist of elements / attributes to remove JS vectors (roughly - making sure that the sanitized document behaves like `<iframe sandbox>` without `allow-scripts`).
 1. Sanitizing the values of the attributes / text content - e.g. URIs, id/name attributes for DOM clobbering in output, limited [script gadget](https://github.com/google/security-research-pocs/tree/master/script-gadgets) vectors sanitization (see e.g. [MUSTACHE_EXPR,ERB_EXPR](https://github.com/cure53/DOMPurify/blob/master/src/regexp.js)).
 1. Special processing for non-HTML e.g. SVG.
 1. Tree conversion and canonicalization with special additional rules to prevent [mXSS](https://cure53.de/fp170.pdf).

Most of the codebase of the sanitizer deals with the above, with special processing to account for browser bugs, or browser API incompatibilities.

Some of the tasks above require userland configuration or hooking for the sanitizer to be useful for its callers. For example:
1. [In-place sanitization](https://github.com/cure53/DOMPurify/commit/42946d225e1b61faab6021246c20f6493a026937) allows the caller of the sanitizer to skip the inert DOM creation [for performance](https://github.com/cure53/DOMPurify/issues/288).
1. Whitelists can be modified by callers to allow application-specific policies (e.g. "we don't want SVGs nor MathML", "we want some custom tags / attributes allowed", "only text-formatting tags", "some scripts are ok").
1. Attribute / content sanitization is usually configurable, either declaratively, or in the form of hooks - this is to allow for [custom URL policies](https://github.com/google/closure-library/blob/36c8ee3896e69a41bda41bd312a567bd8136f237/closure/goog/html/sanitizer/htmlsanitizer.js#L600-L604) ("all network requests should be proxied", "apply a hostname whitelist", "apply a scheme whitelist"), ID/name policies ("we don't care about DOM clobbering", "add a prefix to all IDs", etc.). It gets even more hairy with the gadgets ("remove AngularJS expressions, but we use a different expression separator").
1. Output is sometimes needed as a `DOMFragment`, sometimes as a string etc. This is controlled by the caller. 

The users want a rich customization - that suggests it might be difficult to agree on a "one true HTML sanitizer". Even if we focus on XSS prevention, there are differences between the sanitizers as to whether gadget triggers are "in-scope" (and to what extent), are `data-` attributes OK, which hooks wires to expose, to what extent should a library be concerned with [browser bugs](https://github.com/cure53/DOMPurify/commit/84e30f44e15368a979cfa37d63f86190796e9b74). These concerns are usually easier to satisfy in userland code, than natively.

I think a good starting point would be to expose lower level primitives. I can identify the following:

 1. a proper inert DOM creation API
    * it should not trigger network request or JS execution (now it happens that there are embarrassing browser bugs)
    * it should create the same DOM (now there are some slight differences across browsers)
    * it should solve the [Web Components issue](https://github.com/cure53/DOMPurify/issues/47)
 1. non-clobberable DOM traversing API 
 1. authoritative, browser-mandated elem + attr list
    * at minimum, specifying which element + attribute can result in a network request or a JS execution
    * perhaps exposing it as a map of elem + attribute => Trusted Type? Types already carry that information (`TrustedScript` is a literal JS code, `TrustedScriptURL` will execute JS when loaded, `TrustedURL` may result in a network request etc.)
    * something, something to annotate an attribute can trigger DOM clobbering
    * even if there are browser differences between the lists, it shouldn't matter, as each browser is only required to maintain the list to match its behavior
 1. document serialization that's not prone to mXSS, because, seriously, we should not have mXSS anymore. 

An XSS-focused HTML sanitizer then becomes a lean composition of the above + code to apply the caller-specified customization. That wrapping, customizable sanitizer could be implemented either in userland (where I believe it would be simply easier to maintain), or natively. 

Exposing such primitives has additional advantages:
  * they are easier to polyfill (in fact, that's what the existing sanitizers are doing already)
  * they can be used outside of the HTML sanitization realm. In fact the elem + attr list alone would be very useful for Trusted Type policies, templating systems, or WYSIWYG editors.

**Comment by mozfreddyb** [comment]
We'll keep this in mind, but we've taken a different approach. The individual suggestions make sense to incorporate into e.g., HTML spec (the serialization bits) though. And I think some already have.
