### ISSUE TITLE
Sanitizer argument for `setHTML` optional?

### ISSUE THREAD

**Issue by mozfreddyb** [WICG/sanitizer-api#121]
I think an optional Sanitizer would be useful. We could sanitize using default settings.
(Crazy thought: We might even want to accept a sanitizer config object instead?)

**Comment by otherdaniel** [comment]
I'd be happy either way. But:

As I remember the discussion around `.setHTML`, there was an idea that this effectively becomes the new, better `.innerHTML`, and might very well take on additional parameters in that role. The way the method overload resolution in WebIDL works we'd limit future options quite a bit with optional parameters (which means we'd have fixed the semantics for the no-parameter case) or config option (which is a dictionary, which I think is clashing with some other overloaded types).

The current signature is very conservative with regards to overloading and shouldn't clash with anything else, so we're not precludinbg any future changes to `.setHTML`.

I think one alternate proposal was that there's also one option dictionary as argument, so we'd have `.setHTML("value", { "sanitizer": new Sanitizer() })`. That gives us infinite extensibility, but I find the basic use case to be cumbersome.

As said, I don't feel super strongly either way, but I think there's additional issues to consider.

**Comment by mikewest** [comment]
> I think one alternate proposal was that there's also one option dictionary as argument, so we'd have `.setHTML("value", { "sanitizer": new Sanitizer() })`. That gives us infinite extensibility, but I find the basic use case to be cumbersome.

This seems like the right approach to me, and matches the TAG's recommendations in https://w3ctag.github.io/design-principles/#optional-parameters and https://w3ctag.github.io/design-principles/#prefer-dict-to-bool. Treating `.setHTML("value")` as sanitizing with the default configuration, and making space for a specific sanitizer to be passed in via `.setHTML("value", { "sanitizer": s })` seems pretty reasonable IMO.

**Comment by mozfreddyb** [comment]
I'll change spec text & tests accordingly.

Here's what we got in Firefox @otherdaniel:
```
dictionary SetHTMLOptions {
  Sanitizer sanitizer;
};

partial interface Element {
  [Throws]
    void setHTML(DOMString aInnerHTML, optional SetHTMLOptions options = {});
};
```

**Comment by otherdaniel** [comment]
Makes sense. Will update our implementation accordingly.

**Comment by mozfreddyb** [comment]
Excellent! IIRC, I've allowed myself to adjust the wpt already.

**Comment by mozfreddyb** [comment]
My apologies, this only landed in our integration branch *today*. I don't know the exact cadence of our wpt-sync, but expect it to happen today or tomorrow. The exact changes are at https://hg.mozilla.org/integration/autoland/rev/891f007ad6843fa8d5026cbf7f6ad65401606b46#l9.1, though I suppose I should have touched the idl test as well?
