### ISSUE TITLE
Should `setHTML` return the HTML string?

### ISSUE THREAD

**Issue by mozfreddyb** [WICG/sanitizer-api#123]
While implementing `setHTML`, I was wondering if it would be useful to return the string after parsing (e.g., the element's innerHTML).

Currently, people may (incorrectly) use `foo.innerHTML = blah` and the nature of an assignment expression is that it returns the right hand side of the assignment (i.e., value of blah). The issue is that the RHS will look quite different after parsing.

I think it _might_ be useful to return the parsed HTML string. But I'm happy to be convinced otherwise.

**Comment by otherdaniel** [comment]
You mean Element.setHTML would both modify the element and also serialize the result and return the serialization?

I'd expect the main usage would be to ignore the return value. My main concern would be that we argued for .setHTML to be safe *and* efficient, so it might be counterproductive to add an additional operation (serialization) that will likely only rarely be used. Also, I'd find this generally surprising.

That said, I don't have a super strong argument either way. The notion that `.innerHTML` assignment should be replacable 1:1 certainly also makes sense.

**Comment by otherdaniel** [comment]
Silly idea:

I wonder if it might make sense to default-polyfil this with the comma operator. That is, implement `elem.setHTML` as `(elem.realSetHTML(...), elem.innerHTML)`. That way, the JS compiler "sees" the two operations and has a realistic chance of dropping the 2nd operation if it knows the innerHTML getter is side-effect free and sees the result being unused. I don't think that's (easily) possible if those two ops are inside of a platform method.

**Comment by koto** [comment]
Why shouldn't `foo.innerHTML = bar` be replaced simply with `foo.setHTML(bar)`? It's even shorter than `foo.innerHTML = foo.setHTML(bar)`, so would probably be preferred rewrite anyway.

Stepping back, it's not very idiomatic for the setters to return anything. The pattern that is sometimes seen is for them to return `this` for chaining, jQuery style, but I don't recall recent examples of returning the value set.

**Comment by mozfreddyb** [comment]
Seems like it's most reasonable not to return the string.
