### ISSUE TITLE
setHTML()'s sanitize argument should be optional and probably be turned into a dictionary

### ISSUE THREAD

**Issue by annevk** [WICG/sanitizer-api#130]
@mozfreddyb suggested there might already be agreement around this, but looking at https://wicg.github.io/sanitizer-api/#sanitizer-api it doesn't seem to be in the draft yet. You should be able to call `setHTML()` on an element with just a string and no other arguments. This should end up using the default sanitizer.

**Comment by otherdaniel** [comment]
Done: #138
