### ISSUE TITLE
Consider an append/insert variant

### ISSUE THREAD

**Issue by tjcrowder** [WICG/sanitizer-api#132]
**Very** excited to see this Sanitizer API!

If `.setHTML(x)` is, in some sense, the new `.innerHTML = x`, it probably makes sense to handle the common use case that is currently often (unfortunately) handled with `.innerHTML += x` (but without the antipattern round-trip through markup).

Perhaps `insertHTML`, accepting the same `position` argument that [`insertAdjacentHTML`](https://w3c.github.io/DOM-Parsing/#dom-element-insertadjacenthtml) takes:

```
partial interface Element {
  undefined insertHTML(DOMString position, DOMString input, Sanitizer? sanitizer);
};
```

It may need to throw if called with `position` set to `"beforebegin"` or `"afterend"` if the element it's called on doesn't have a parent (yet), since as I understand it the sanitizer needs to know what element it's sanitizing for.

Example:

```js
document.getElementById("x").insertHTML("beforeend", userInput);
```

It's tempting "just" to add a third optional argument to `insertAdjacentHTML`, but `setHTML` sanitizes whether it has that sanitizer argument or not, whereas `insertAdjacentHTML` doesn't, so probably best if it's separate.

(Apologies if I've missed previous discussion on this, as seems likely. Didn't find anything relevant in the issues or Q&A.)

**Comment by koto** [comment]
`innerHTML += ` has these side effects too, no? I think it mostly exemplifies why dynamically appending to a node is not a best practice, and sanitizer just doesn't make this easier than it could.

**Comment by annevk** [comment]
Adding `beforeHTML()` and such make sense to me, not sure we need to track it here.

**Comment by annevk** [comment]
Oh, let's fold this into #184.
