### ISSUE TITLE
Example 13 and many other uses of santize() out of date

### ISSUE THREAD

**Issue by hamishwillee** [WICG/sanitizer-api#133]
Just FYI example 13 still assumes `sanitize()` takes a string rather than a domnode.

```

  const sample = "Some text <b><i>with</i></b> <blink>tags</blink>.";

  // Some text <b>with</b> text tags.
  new Sanitizer({allowElements: [ "b" ]}).sanitize(sample);

  // Some text <i>with</i> <blink>tags</blink>.
  new Sanitizer({blockElements: [ "b" ]}).sanitize(sample);

  // Some text <blink>tags</blink>.
  new Sanitizer({dropElements: [ "b" ]}).sanitize(sample);

  // Note: The default configuration handles XSS-relevant input:

  // Non-scripting input will be passed through:
  new Sanitizer().sanitize(sample);  // Will output sample unmodified.

  // Scripts will be blocked: "abc alert(1) def"
  new Sanitizer().sanitize("abc <script>alert(1)</script> def");
```

Further, if you implement `to_node()` as per the spec in order to try this, the sanitize() method recognizes that the argument is not a `Document` or `DocumentFragment`. Upshot, technically none of the examples work. 
IN case I am doing something wrong, this is the code fragment that is reporting that param1 is not correct type:
```js
const to_node = str => (new DOMParser).parseFromString(str, "text/html").body.firstChild;
const sample = "Some text <b><i>with</i></b> <blink>tags</blink>.";
sample_node = to_node(sample);
let mySanity = new Sanitizer();
let result = mySanity.sanitize(sample_node);
```

There are lots of minor typos and similar issues in this spec. Is it worth be bothering to report at this time?

**Comment by otherdaniel** [comment]
Thanks! I've updated the examples, and fixed minor language issues where I saw them.

Yeah, the examples (& other spec parts) went through several revisions, and I see I didn't adapt them up as well as I thought. I suspect there'll be a bit more churn before the spec settles down. That said, we're happy for any help we can get. None of the spec editors are native English speakers, so help with editorial and language issues are particularly welcome!

> Is it worth be bothering to report at this time?

I promise to fix every single issue you find. :)
