### ISSUE TITLE
Have the API interface follow W3C Platform Design Principles

### ISSUE THREAD

**Issue by Schepp** [WICG/sanitizer-api#136]
In its W3C Platform Design Principles, in § 6.3, [the W3C suggests using dictionary arguments instead of a series of optional primitive arguments](https://www.w3.org/TR/design-principles/#prefer-dict-to-bool). Example:

```js
Thing.method(a, b, c); // old-school
```

vs.

```js
// the modern, suggested way
Thing.method({
  arg1: a,
  arg2: b,
  arg3: c
});
```

The advantages of dictionary arguments being:

1.) Easier to remember where to put certain values
2.) Easier to omit values
3.) Order of arguments is not important
4.) Better future extensibility with more optional arguments

Therefore my suggestion would be to rework the planned interface like so:

```js
document.getElementById("target").setHTML(user_string, {
  sanitizer: sanitizer,
});
```
(keeping the first primitive parameter for the intended compatibility with `innerHTML`)

and

```js
sanitizer.sanitizeFor({
  context: "div", 
  userString: user_string,
});
```
(camel-case as [per W3C Platform Design Principles § 12.5](https://www.w3.org/TR/design-principles/#casing-rules). Could as well just be `string`)

**Comment by mozfreddyb** [comment]
Yeah, I think this is #121 :grimacing:
