### ISSUE TITLE
.sanitizeFor and namespaces

### ISSUE THREAD

**Issue by otherdaniel** [WICG/sanitizer-api#140]
Currently, `.sanitizeFor` is specified as always creating elements in the HTML namespace. Following PR #137 that is a bit surprising. It also divorces `.sanitizeFor` from `Element.setHTML`.

Options might be:
- Leave it as is.
- Also recognize namespace designators. (The same as for configuration items.)
- An API similar to `.createElementNS`.

**Comment by mozfreddyb** [comment]
Which piece exactly makes it another argument for deferring?
I want to point out that we already need to parse namespace-y element names when accepting a Sanitizer config, like in #137

**Comment by annevk** [comment]
In the sense that we haven't decided on a shape for this for an eventual new element-creation API.

I'm also not sure #137 is entirely correct. I think it would be better if the API was case-sensitive and not needed special HTML/XML document branching.
