### ISSUE TITLE
Consider the impact of https://github.com/whatwg/dom/issues/849

### ISSUE THREAD

**Issue by otherdaniel** [WICG/sanitizer-api#142]
Consider the impact of "Valid/Invalid characters in document.createElement()" (https://github.com/whatwg/dom/issues/849) on the Sanitizer. (Once that issue gets resolved.)

**Comment by annevk** [comment]
I think we should essentially not validate the strings. Just use them for straight up comparison. That way we sidestep this entirely.

**Comment by mozfreddyb** [comment]
I agree.

**Comment by freddyb** [comment]
We all seem to agree that we shouldn't validate the strings. Closing.

**Comment by mozfreddyb** [comment]
We all seem to agree that we shouldn't validate the strings. Closing.
