### ISSUE TITLE
setHTML taking sanitizer object directly inconsistent with definition

### ISSUE THREAD

**Issue by hamishwillee** [WICG/sanitizer-api#143]
as per https://wicg.github.io/sanitizer-api/#dom-sanitizer-sanitizer `setHTML` takes an options object (that contains a sanitizer property). 

Many of the examples however take a sanitizer directly (rather than in an options argument). For example, `Example 1`.

This actually works in Chrome and Firefox, but is undocumented. Can we either add explicit support for this or remove from the examples?

This flows out of an MDN docs issue: https://github.com/mdn/content/issues/15414

**Comment by otherdaniel** [comment]
Those APIs have changed, and I didn't update the examples correctly. I'll fix that.

It seems those APIs are presently being reconsidered,  but any spec draft should certainly be self-consistent.

As I read it, it's the `setHTML` method that takes an options dictionary with a `"sanitizer"` property. The constructor takes a dictionary with the sanitizer options, but has no `"sanitizer"` property.

**Comment by hamishwillee** [comment]
> As I read it, it's the setHTML method that takes an options dictionary with a "sanitizer" property. The constructor takes a dictionary with the sanitizer options, but has no "sanitizer" property.

Yes!

**Comment by otherdaniel** [comment]
Should be fixed now.

Please let us know if you find additional inconsistencies; I'll gladly fix them.

**Comment by otherdaniel** [comment]
Note: The continuous build thingy is error-ing out, so it may take a bit for this to show up in the online version.

**Comment by hamishwillee** [comment]
> Please let us know if you find additional inconsistencies; I'll gladly fix them.

Thank you. I'm not looking at this with a close eye right now but I certainly will next time I do an update. Hopefully that won't be too long as MDN is not up to date since configuration options became officially supported: https://github.com/mdn/content/issues/15500
