### ISSUE TITLE
More consistent capitalization & normalization handling

### ISSUE THREAD

**Issue by mozfreddyb** [WICG/sanitizer-api#145]
Case-handling is inconsistent between attributes and elements. Furthermore, both are meant to be case-sensitive in the spec. We'd have issues with non-existing elements/attributes that are lower-case spelling of *known* mixed-case elements.

I suggest we stop normalizing or lowercasing names completely and switch to case-sensitive comparisons. 
From a cursory search, all other Web APIs are also case-sensitive (e.g., Mutation Observer).

**Comment by annevk** [comment]
New APIs, such as mutation observer, are generally case-sensitive and operate on local name. Similar to `document.createElementNS()`, say. The APIs you mentioned above are all rather messy and not considered precedent to follow.

cc @domenic

**Comment by mozfreddyb** [comment]
I think this is resolved as per #163 and the related wpt changes.
