### ISSUE TITLE
can we rename this to sanitizer?

### ISSUE THREAD

**Issue by mozfreddyb** [WICG/sanitizer-api#16]

**Comment by otherdaniel** [comment]
If this is about naming: +1 for renaming.

(I think both "sanitizer" and "purify" have some unfortunate connotations, but I can't really think of a name that doesn't and is still reasonably common for this functionality. I think "input sanitization" is the most commonly used technical term for this.)

If this is about GitHub, whether you can rename an existing repository: I don't know. :)

**Comment by otherdaniel** [comment]
Obsolete.
