### ISSUE TITLE
How to identify elements to allow/block?

### ISSUE THREAD

**Issue by otherdaniel** [WICG/sanitizer-api#17]
The current draft identifies elements and attributes by name + namespace. But [Custom Elements](https://html.spec.whatwg.org/multipage/custom-elements.html) allow to [customize built-in elements](https://html.spec.whatwg.org/multipage/custom-elements.html#custom-elements-customized-builtin-example) with a different name.

(In Trusted Types, we decided to go by the constructor name of the base element.)

**Comment by mozfreddyb** [comment]
Do we expect Custom Elements to be added individually and explicitly or do you think we require a switch to allow all custom elements?

**Comment by otherdaniel** [comment]
Not sure, honestly.

I guess this is the type of question where I'd like to get user (web dev) feedback, because I'm not entirely sure I fully understand the problem.

For TT, if I remember correctly, the result was that the constructor name of the type that the attribute is defined on is used. So if you have some custom element `bla` that derives from `HTMLScriptElement`, and you call `.src`, then the callback gets `HTMLScriptElement.src`, not `bla.src` or `script.src`. I was kinda hoping that this could be generalized, so that blocking `HTMLScriptElement` would also block custom elements derived from it. But as said above, I'm not really sure if that is what users would expect.

**Comment by otherdaniel** [comment]
I tried to resolve this issue, by specifying that elements get identied by their constructor name, and then - for custom elements - first run the check with their own constructor, then with the lowest DOM-defined constructor in the constructor chain.

For example, my-script (with MyScript which extends HTMLScriptElement) would be blocked if either MyScript or HTMLScriptElement is blocked.

I thought that's a good idea, until I noticed that most "normal" HTML elements (like <b>, <em>, etc.) are all HTMLElement, and thus the config would no longer be able to distinguis those. That doesn't sound useful.

So: I think we should stick to local names (or qnames, or somesuch). The general idea of checking a custom element both on its own and for its parent tag still seems like a good idea to me.

**Comment by mozfreddyb** [comment]
Yeah, let's operate on a local name and have an explicit if-branch for custom elements.

**Comment by otherdaniel** [comment]
After (re-)reading [Custom Elements](https://html.spec.whatwg.org/multipage/custom-elements.html) I came to the conclusion that custom elements don't actually work how I thought they do. In particular, I thought that the XSS-potential from custom elements would derive mainly from having a custom element derive from built-ins (e.g., have a <my-script> element that's really a <script>, which the Sanitizter then wouldn't know about), but it seems that "customized built-in elements" can't actually invent a new tag name, while "autonomous custom elements" can, but they don't inherit XSS-y behaviour. With that, the real XSS threat would not be injection-by-script content, but by triggering the site-supplied JS. If so, the best option would seem to be a general on/off switch.

I'm trying to formalize this by referencing the custom element lookup from the DOM spec. I'll send a PR shortly.
