### ISSUE TITLE
how about sanitizer-api add deny sql injection code rules

### ISSUE THREAD

**Issue by k4n5ha0** [WICG/sanitizer-api#179]
In some finance internally piloting  webapp standard，webapp js deny sqli and xss input and report an emergency
so i suggest sanitizer-api can add rules for sqli  whith sqli tokenizer parser analyzer like libinjection

**Comment by mozfreddyb** [comment]
The Sanitizer runs in the browser and most SQL is happening in the server.
We're tackling frontend bugs here.

Furhtermore, this Sanitizer has a very specific goal to prevent XSS and only that.
Our threat model is intentionally a bit weaker in the interest of incremental progress.
Please read the "Security Considerations" section of our spec.
