### ISSUE TITLE
Cross-cutting concern: Ensure forward/backward compatibilty.

### ISSUE THREAD

**Issue by otherdaniel** [WICG/sanitizer-api#19]
I suspect there will be a compability risk (across versions; not browsers), particularly for the pre-defined filter lists. When a browser adds e.g. a new event type & associated event handler, then the filter lists need to be updated as well. This might have surprising consequences for app developers.

**Comment by otherdaniel** [comment]
I'm not sure if there can be a "universal" mitigation against such risks, but as a general strategy I'd propose to:

- Make sure that the sanitizer(s) have no implied behaviour (that is, all behaviour can be configured).
- The default filter lists then essentially become default configs.
- Compatibility then becomes a rule that existing configs need to preserve existing behaviour.

**Comment by mozfreddyb** [comment]
Existing configs need to preserve existing behavior and a default config implying a default filter list does not add up to me. A default list will evolve over time.

So, here's what I think we can expect for forward compat whenever a new element/attribute is proposed (implemented):
In any case, we need to make well-documented decisions whether those elements are going to be allowed or not.
I think we also need to accept that browsers will add new elements/attributes at their own pace. There will to be a difference in elements that are understood and meaningful per-browsers (there probably already is. Thinking of `<portal>`, which is behind a pref in Chrome).

Now the question is, how do browsers deal with elements/attributes they do not understand: In the light of a whitelist-based sanitization, do we expect every browser to have an up-to-date list (maybe even including contenious or experimental elements) regardless of their support? 
The alternative, which I'd prefer, is to accept that there is a difference in behavior for those elements. Particularly, to reduce maintenance burden on the spec & the browsers that implement the spec and additionally, to further discourage users of the Sanitizer API to store and serve previous sanitizer results to other users.

**Comment by mozfreddyb** [comment]
While we will take this into account in perpetuity, the issue here as written is not directly actionable. Closing.
