### ISSUE TITLE
Ability to configure whether script elements should execute

### ISSUE THREAD

**Issue by zcorpan** [WICG/sanitizer-api#195]
Currently `innerHTML` and `insertContextualFragment()` will not execute `script` elements because:

https://html.spec.whatwg.org/#script-processing-model:already-started-4 sets "already started" to true when the element is inserted into the temporary document during fragment parsing, and step 17 returns because scripting is disabled for that document. Then when the elements are inserted into the right place, "already started" is still true and https://html.spec.whatwg.org/#script-processing-model:already-started-3 returns.

`Range.createContextualFragment()` unsets the "already started" flag and therefore runs scripts: https://w3c.github.io/DOM-Parsing/#dom-range-createcontextualfragment (step 4).

In today's meeting, we discussed this for `setHTML()` and the group's general agreement was that we should align with `innerHTML` by default but in the future we can allow a config to make `script` elements execute.

**Comment by mozfreddyb** [comment]
I think this is resolved by `setHTML` / `parseHTML` making use of `setHTMLUnsafe` and `parseHTMLUnsafe` which already do not support `<script>` directly. Is that correct?

**Comment by annevk** [comment]
They do not execute `script`, but they are aligned with `innerHTML` in that a `script` element will be in the resulting node tree. And as such the suggestion continues to be a valid one, should there be web developer demand.

**Comment by Sora2455** [comment]
I assume that people are asking if `setHTMLUnsafe()` should have an escape hatch that allows script execution, and not `setHTML()`? Letting `setHTML()` execute scripts seems like it would let it fail at the very core of its job.

**Comment by annevk** [comment]
Yeah, that's a good point. And no need to track this here either as the relevant APIs are defined in the HTML Standard, not here.

**Comment by zcorpan** [comment]
Moved to whatwg/html: https://github.com/whatwg/html/issues/10090
