### ISSUE TITLE
2023-09-20 meeting notes

### ISSUE THREAD

**Issue by evilpie** [WICG/sanitizer-api#199]
[Issue #198: Configuration edge cases](https://github.com/WICG/sanitizer-api/issues/198)
One of the main results of this discussion was that having attributes both for allowElements and blockBlements doesn’t really work.
Should we block an element with a specific attribute, or just drop the attribute? But why would it be called blockElement then?
This is “Block-clauses with element-dependent attributes” in the linked issue.

**New design with elements and attribute properties**
- Use `elements` instead of `allowElements`
  - Every element can have allowed/dropped attributes
- Use `attributes` instead of `allowAttributes`
  - Every attribute can also have “elements” i.e. the list of elements this attribute is allowed for
```javascript
{ 
  elements: ["img", // allow all <img> tag
             { name: "animate", namespace: "http://www.w3.org/2000/svg" }, // allow all SVG <animate> elements
             { name: "b", attributes: ["title"] }, // Allow <b> elements, but remove all of the attributes except "title".
             { name: "a", dropAttributes: ["href"] }], // Allow <a> elements, allow all default attributes, but drop "href"

  attributes: ["title", // Allow title on all elements
               {name: "href", elements: ["a"] }] // Allow the href attribute only for <a> elements
}
```

- We still have `dropAttributes`, `dropElements` and `block`/`flattenElements`.
  - `dropAttributes` doesn't allow `elements` and `drop/flattenElements` doesn't allow `attributes` as filters!

```javascript
{
  flattenElements: [ /* like dropElements */],
  dropElements: [
    { name: "input"}, // drop all input elements
    { name: "animate", namespace: "http://www.w3.org/2000/svg"}, // drop all SVG animate elements
    "b", // drop all b elements
  ],
  dropAttributes: ["style", // never accept style attrs
                   { name: "type", namespace: "http://www.w3.org/2000/svg"}] // Don't accept type attributes in the SVG namespace
}
```

Tom: This means the “happy path” uses just the terms “elements” and “attributes”, which is both short and easy to remember

**Rename block**
- We don’t have `allowElements`/`allowAttributes` anymore so we don’t need the symmetry with allow.
- Call “block” (replace with children) something like "flat"/"flatten" like JS [flatMap](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap)
Anne: my concrete proposal here is flattenElements
- So we end up with elements/dropElements/flattenElements and attributes/dropAttributes

This is overall a bit similar to the proposal in https://github.com/WICG/sanitizer-api/issues/181 and in Firefox: https://searchfox.org/mozilla-central/source/dom/webidl/Sanitizer.webidl

**Comment by mozfreddyb** [comment]
> ## block vs. allow:
> 
> Both block and allow list are needed. Block should have precendence over allow.
> 

Please note that whatever is being specified as a custom Sanitizer configuration will be held against the secure defaults. This means developers will not be able to allow `<script>` elements when using `setHTML()`.
