### ISSUE TITLE
Should the sanitizer normalize

### ISSUE THREAD

**Issue by annevk** [WICG/sanitizer-api#203]
See #202 for context. Someone(tm) should probably look at what ranges do as they have similar multi-node mutation operations.

**Comment by otherdaniel** [comment]
Ranges apparently don't normalize, or at least `Range.insertNode` doesn't.

spec: https://dom.spec.whatwg.org/#concept-range-insert

impl:
```
d = document.createElement("div");
d.textContent = "abcdef";
d.childNodes.length   // 1, as expected

r = document.createRange();
r.setStart(d.firstChild, 3);  // position range in the middle of the text node.
r.insertNode(document.createTextNode("XXX"));
d.innerHTML  // "abcXXXdef"
d.childNodes.length  // 3
```

**Comment by annevk** [comment]
@smaug---- @rniwa thoughts?

**Comment by mozfreddyb** [comment]
Without anyone being of a strong opinion and the web platform mostly not normalizing, we will also just not normalize.

**Comment by mozfreddyb** [comment]
I guess this is resolved and does not need any further action.
