### ISSUE TITLE
Trusted types API interaction 

### ISSUE THREAD

**Issue by lukewarlow** [WICG/sanitizer-api#204]
The explainer and probably the spec should mention how this API interacts with the trusted types API.

~~I would expect that this API should be able to be used inside of the policies from trusted types but this isn't clear from the spec.~~ Given both APIs are designed to address XSS first and foremost it feels like this should definitely point to that API.

After reading some more it seems this API doesn't provide a string to sanitized string function and so can't be used in trusted types policies? If this is the case it should be explained why that is.

**Comment by Sora2455** [comment]
I feel like the two APIs should integrate in one of two ways:

- `element.setHTML` and `Document.parseHTML` aren't a TrustedTypes sink, but `element.setHTMLUnsafe` and `Document.parseHTMLUnsafe` are
- There should be some way to directly integrate a santizer into the createHTML method of trusted types - e.g., returning a sanitizer config instead of a string

The first way seems far more straightforward to me.

**Comment by koto** [comment]
> I feel like the two APIs should integrate in one of two ways:
> 
> * `element.setHTML` and `Document.parseHTML` aren't a TrustedTypes sink, but `element.setHTMLUnsafe` and `Document.parseHTMLUnsafe` are

This is the way.

**Comment by mozfreddyb** [comment]
So we should add the unsafe methods to TT and move this issue over. What else is lefet to do here?

**Comment by lukewarlow** [comment]
I think the spec or explainer should add an explicit call out to the trusted types API, to show that there's been thought put into which is a sink and which isn't

**Comment by lukewarlow** [comment]
I agree that unsafe should be a sink by default (this has been added to the spec because they're already in html), I do wonder if unsafe plus an appropriate filter should be considered trusted?

Likewise should safe by trusted by default (I think this depends on the browser baseline safety)? If the baseline removes event handler attributes and scripts then trusted by default makes sense.

**Comment by annevk** [comment]
Making unsafe plus an arbitrary filter be safe seems like way too much complexity to be worth the effort. Just use the non-unsafe variant.

And what is safe is not implementation-defined (it will be defined in detail), so what @Sora2455 and @koto wrote is indeed the way.

As for an explicit callout, that might make sense. Though I would expect most of this specification to be folded into HTML in due course.

**Comment by lukewarlow** [comment]
I'm going to go ahead and close this out. I think once upstreamed a note explaining why the safe variants don't use Html string could be useful, even if just as a note to make it clear it's a deliberate choice.
