### ISSUE TITLE
Unpublish current spec?

### ISSUE THREAD

**Issue by lukewarlow** [WICG/sanitizer-api#207]
The currently published spec no longer matches the expected API shape described in https://github.com/WICG/sanitizer-api/blob/main/explainer.md

Ideally that explainer should be translated into a bikeshed format and published but in the meantime I think it would be useful to unpublish or otherwise mark as deprecated the currently published spec.

**Comment by lukewarlow** [comment]
The new spec should also ideally make reference to trusted types to explain the expected integration.

I would imagine that `setHTML` and `parseHTML` would not require trusted types as they're effectively covered by a browser provided policy?

**Comment by mozfreddyb** [comment]
@otherdaniel is working on a rewrite that will hopefully become a Pull Request very soon. See https://github.com/otherdaniel/purification/tree/spec-rewrite for a sneak preview 🙂.

**Comment by mozfreddyb** [comment]
@otherdaniel Any updates on your upcoming PR? I'd like to close this one out.

**Comment by mozfreddyb** [comment]
#208.
