### ISSUE TITLE
Overloading methods in a separate partial definition is invalid

### ISSUE THREAD

**Issue by tidoust** [WICG/sanitizer-api#209]
The Sanitizer API overloads methods already defined in HTML, such as `Document.parseHTMLUnsafe()` ([HTML](https://html.spec.whatwg.org/multipage/dom.html#document), [Sanitizer API](https://wicg.github.io/sanitizer-api/#dom-document-parsehtmlunsafe)).

That is forbidden by Web IDL: it imposes that "Operations must not be overloaded across interface, partial interface, interface mixin, and partial interface mixin definitions." (see [Overloading](https://webidl.spec.whatwg.org/#idl-overloading)).

I suspect that you're doing that on purpose, know what you're doing, and that the final goal is to upstream these definitions to HTML. I also don't see any immediate workaround (apart from relaxing the constraint in Web IDL, perhaps?)

In the meantime, I note that this creates a practical problem: the updated IDL defined in the Sanitizer API cannot reach Web Platform Tests ([`interfaces/sanitizer-api.idl`](https://github.com/web-platform-tests/wpt/blob/master/interfaces/sanitizer-api.idl)) because one of the guarantees that we enforce in [Webref](https://github.com/w3c/webref) on the way to Web Platform Tests is that the Web IDL as a whole, merging the IDL defined across specs, is valid.

**Comment by annevk** [comment]
Can we annotate them in some way that they're not indexed? It shouldn't really matter until it's standardized.

**Comment by otherdaniel** [comment]
Would this work? https://github.com/WICG/sanitizer-api/pull/210 

That looks a bit dorky, since it just renames the methods in questions by adding a `__TO_BE_MERGED` suffix. But it should make the tools happy again.
