### ISSUE TITLE
Current State of `config`/`options` for proposed API

### ISSUE THREAD

**Issue by shgysk8zer0** [WICG/sanitizer-api#215]
Just wanting clarification on which represents the currently proposed API...

## `el.setHTML(html, { elements, attributes, ...etc })`
![Screenshot from 2024-04-08 15-13-47](https://github.com/WICG/sanitizer-api/assets/1627459/7f2795b7-ae68-431e-b47f-dc6970a1f8c1)

![Screenshot from 2024-04-08 15-12-47](https://github.com/WICG/sanitizer-api/assets/1627459/1e25a0cb-8b0a-47b5-866b-d920fa0da94c)

## Or `el.setHTML(html, { sanitizer: { elements, attributes, ...etc }})`
![Screenshot from 2024-04-08 15-13-47](https://github.com/WICG/sanitizer-api/assets/1627459/78b3d919-2995-4bed-90c6-dc4e252aa578)

**Comment by annevk** [comment]
The latter is the plan, see https://github.com/WICG/sanitizer-api/pull/211.

**Comment by otherdaniel** [comment]
#211 has been merged, with updates to explainer & proposed spec.

I think this section of the explainer is most relevant: https://github.com/WICG/sanitizer-api/blob/main/explainer.md#configuration-options-sanitizer-object-or-dictionary 

@shgysk8zer0 Please let me know if spec or explainer are still unclear.
