### ISSUE TITLE
Remove __TO_BE_MERGED variants

### ISSUE THREAD

**Issue by foolip** [WICG/sanitizer-api#216]
`setHTMLUnsafe` and `parseHTMLUnsafe` are in HTML since https://github.com/whatwg/html/pull/9538, with the difference that the optional dictionary isn't there.

What remains to remove these variants from this spec?

I ask because I'm writing a patch to exclude them from `@webref/idl`.

**Comment by foolip** [comment]
Yes, I saw those explaining these names, but the question is when these variants will be removed entirely?

**Comment by annevk** [comment]
When they are merged into HTML.

**Comment by foolip** [comment]
Is that (the 2nd dictionary arguments, I guess) tracked by some issue that is still open?

**Comment by annevk** [comment]
https://github.com/whatwg/html/issues/7197

**Comment by foolip** [comment]
Thanks @annevk!
