### ISSUE TITLE
faq.md is outdated

### ISSUE THREAD

**Issue by lukewarlow** [WICG/sanitizer-api#221]
The faq.md file is outdated, it should be updated or possibly just deleted?

**Comment by mozfreddyb** [comment]
I think our explainer might be enough. The FAQ was written by @otherdaniel, so I'd like him to comment too :)

**Comment by otherdaniel** [comment]
Yeah, that's outdated. I'd suggest to delete it for now, and to reinstate it once we see questions getting frequently asked.
