### ISSUE TITLE
Renaming methods to prefix them with `add` make it clear there is a modification of the instance

### ISSUE THREAD

**Issue by mozfreddyb** [WICG/sanitizer-api#238]
I am filing this on behalf of @annevk who was making this point in an earlier meeting:

> The suggestion was to rename methods to `addElement`, `addRemoveElement`, `addReplaceWithChildrenElement`, etc. (prefix with add to make it clear there is a modification of the instance)

I suggest we do this independent of #237, so I'm splitting this out.

I'm also asking everyone to wait for @annevk to describe this further so we are not arguing against a strawman.

**Comment by annevk** [comment]
Proposals:

* `element()`
* `removeElement()`
* `comment()`

---

* `addElement()`
* `addRemoveElement()`
* `setComment()`

---

* `appendElement()`
* `appendRemoveElement()`
* `setComment()`

---

* `addToElements()`
* `addToRemoveElements()`
* `setComment()`

---

* `allowElement()`
* `removeElement()`
* `replaceWithChildrenElement()`
* `setComment()`

(I don't like this last one as it's not internally consistent.)

**Comment by benbucksch** [comment]
I'm assuming this is referring to this part of the spec:
```idl
dictionary SanitizerConfig {
  sequence&lt;SanitizerElementWithAttributes> elements;
  sequence&lt;SanitizerElement> removeElements;
  sequence&lt;SanitizerElement> replaceWithChildrenElements;

  sequence&lt;SanitizerAttribute> attributes;
  sequence&lt;SanitizerAttribute> removeAttributes;

  boolean comments;
  boolean dataAttributes;
};
```


However, that also doesn't explain what these functions actually do. Could there be some JavaDoc-style comment in human-readable English (no pseudo-code)?

What does this actually do?
1. Does it add or remove a DOM element, immediately, once? 

If so, then:
* `addElement()`
* `removeElement()`

2. Does it modify the list of DOM elements to filter? It applies not immediately, but whenever somebody adds DOM elements in whatever way?

If so, then:
* `addElementFilter()`
* `removeElementFilter()`

**Comment by benbucksch** [comment]
Or, for 2., alternatively:
* `allowElement()`
* `denyElement()`

It's completely unclear to me what `replaceWithChildrenElement()` is supposed to do.

**Comment by annevk** [comment]
No, this is in relation to #237.

**Comment by benbucksch** [comment]
OK. From what I understand from #237, this is about modifying the filter lists (allow lists and deny lists), right? If so:

My suggestion would be:
* `allowElement(element)`
* `denyElement(element)`

And for clearing maybe (ideas):
* `resetToDefaults()` (deletes all config entries, and sets default safe filters)
* `allowAllUnsafe()` (deletes all config entries, and allows everything, including unsafe HTML)
* `allowOnlyElements(element[])` (deletes all config entries, sets default safe filters, adds a default-deny filter, and adds all the given elements as `allowElement()`)

**Comment by mozfreddyb** [comment]
What is the internal consistency issue in (E)?

I would prefer (A) and (E), as I find terminologies like `addRemove` or `appendRemove` quite counter-intuitive.

**Comment by otherdaniel** [comment]
For me: (A) + (E) are preferred; then (D), then (B) and (C). I'm happy to go with the majority, though.

> What is the internal consistency issue in (E)? 

The dictionary has `elements` and `removeElements` (rather than `allowElements`. The allow forms drop the verb.); while (E) has verbs everywhere. If we do settle for (E), I think we should resolve this by making the dictionary say `allowElements`, too.

**Comment by annevk** [comment]
I think the dictionary experience would be worse with `allowElements`. And I also think the dictionary experience is more important.

My preference order: B, C, D, A, E.

Arguably Fetch's `Body` mixin is precedence for the naming in A, but the methods on `Body` don't (really) manipulate. They return data. I think it's quite confusing to have methods whose primary purpose is manipulation to not indicate that in any way.

Looking at E, while say `replaceWithChildrenElement` has a verb in it, it doesn't actually describe what it does. It manipulates the internal replaceWithChildrenElements list (plus possibly some adjacent bookkeeping), but that is not what that name indicates.

**Comment by mozfreddyb** [comment]
Would we get to a somewhat saner place if we went with terminology that focuses on the use-case, replacing-with-children(blocking), removing, ... rather than list operations?

**Comment by mozfreddyb** [comment]
In today's meeting, Guillaume, Daniel, Anne and I agreed on the following changes to be made to #237:


**change**
*  replaceWithChildrenElements to replaceElementWithChildren()
*  setComments() to plural.

**keep:**
- removeElement()
- allowElement()
- removeAttribute()
- allowAttribute()
- setDataAttributes()

We are all very happy and relieved now and will close this one out once #237 has merged.
