### ISSUE TITLE
HTML5lib-style test cases for Sanitizer API WPT tests

### ISSUE THREAD

**Issue by otherdaniel** [WICG/sanitizer-api#241]
This issue is to track progress on using HTML5lib-style test cases for Sanitizer's WPT test cases.

Specififcally, this format:  https://github.com/html5lib/html5lib-tests/blob/master/tree-construction/README.md

**Comment by otherdaniel** [comment]
I have two, hacky versions of how I think it could work:

1, Re-using the logic for webvtt/parsing/cue-text-parsing WPT tests
  - This requires a Python script to pre-process the test cases.
  - It seems the webvtt support library has some oddities that doesn't quite conform to how html5lib describes the format.
  - Hacky version here: https://chromium-review.googlesource.com/c/chromium/src/+/5905062

2, Doing it all in JS.
  - Test data in a `<script>` element in the same file that uses it.
  - Hacky version here: https://chromium-review.googlesource.com/c/chromium/src/+/5904239

In the call, Tom pointed out two issues, IMHO both correct:
- The `<script>`-version cannot handle handle "</script>" tags in source without some extra logic.
- Neither can handle closed shadow-roots, since... they're closed.

(I'm happy to convert the source to WPT GitHub-PRs, if that helps.)

**Comment by annevk** [comment]
Why not do 2, but have the test data in an external file? That makes it easier for others to reuse and does away with the `</script>` issue.

I wonder if we can handle closed shadow roots by getting references to them during setup, but I also think it would be okay if we have some tests on the side for shadow roots.

**Comment by josepharhar** [comment]
+1 to not having a python script if it's not a lot of work 😅 

I've made small parser tests which don't use any sort of format like [this one](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/web_tests/external/wpt/html/semantics/forms/the-select-element/customizable-select/select-parsing.tentative.html;drc=50b3bfe0fdc81e9b62bb3e00c6b80632cc89c6b5), but yeah seems good to reuse this format if you want to have more test cases that are easier to iterate on.

**Comment by annevk** [comment]
I think for the `select` enhancement in particular we should have https://github.com/html5lib/html5lib-tests coverage instead, but that's a bit off-topic for this issue.

**Comment by otherdaniel** [comment]
Fleshed out the code a bit more. It can now parse a string, with convenience methods to either get it from a `<script>` element, or from a Promise of a Response, as `fetch()` would return. That way, the user can pick whichever source is appropriate.

I intend to land this as a support file for Sanitizer API tests. But it's written so that it should be easy to generalize and make it more generally useful within WPT. Current version here: https://chromium-review.googlesource.com/c/chromium/src/+/5920436

**Comment by otherdaniel** [comment]
Test case support landed here: https://github.com/web-platform-tests/wpt/blob/master/sanitizer-api/support/html5lib-testcase-support.js

Example test cases:
- https://github.com/web-platform-tests/wpt/blob/master/sanitizer-api/sanitizer-basic-filtering.tentative.html
- https://github.com/web-platform-tests/wpt/blob/master/sanitizer-api/sethtml-tree-construction.dat

We'll need more test cases, and I'll add a few more soon. This particular issue is about whether & how to use html5lib-style tests, and I think that issue has been resolved. Will close.
