### ISSUE TITLE
Chainable modifiers?

### ISSUE THREAD

**Issue by otherdaniel** [WICG/sanitizer-api#242]
This came up when editing the "modify-able config" PR, #237: Should the modifier methods return a reference to [=this=], so that you can 'chain' methods?

```js
sanitizer.allowElement("a").allowElement("span");
```

A precedent might be [JavaScript Set type](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/add)

**Comment by annevk** [comment]
The web platform doesn't do this. We reserve return values in case we might want to return something useful at some point.

See https://github.com/w3ctag/design-principles/issues/286.
