### ISSUE TITLE
Handling of Defaults

### ISSUE THREAD

**Issue by otherdaniel** [WICG/sanitizer-api#29]
How should defaults be handled? 

Had a brief discussion with @iVanlIsh about this, and there seem to be two trains of thought:

1. Just have a single, well-chosen default, so that developers can simply call `sanitize(...)` and get good results.
2. There isn't really a single, obvious default, but rather a handful of base use-cases. E.g., plain text-only; simple formatting; anything-goes-except-JS. There should be default-configs for each of those, instead of a single global default.

 I think the main consideration here is developer ergonomics, on both sides: The first is really, really simple. The second takes the point of view that this is arguably too simple, and that set-of-defaults is better suited,

The current version of the explainer reflects no. 2 above, which happens to be my opinion. However, we don't have consensus yet.

**Comment by koto** [comment]
The web keeps changing, I don't think there's a way to define a sanitizer
config that satisfies any complex goal (e.g. no xss) that would still work
after a few years. If this was possible, we would not have constant updates
to existing xss sanitizers.

**Comment by iVanlIsh** [comment]
I feel that we do not need two separate APIs as Sanitizer and defaultSanitizer, and the Sanitizer could be created by three different ways:
1. Sanitizer can be created without any config `new Sanitizer()` which will lead to most strict rules ( forbid almost everything ), which allow developers easy to get start with.
2. Have several default settings with a name, so that Sanitizer can be created by a simple name other than the detailed configs: `new Sanitizer("string_only")`
3. Create a fully customized one with the full definition of configurations: `new Sanitizer({allow_attr:..., ban_attr:...,.......})`

**Comment by otherdaniel** [comment]
> I feel that we do not need two separate APIs as Sanitizer and defaultSanitizer, [....]

Maybe this is a misunderstanding of the present proposal: The idea is that `new Sanitizer(options)` is the only way to create a sanitizer. It's just that there's a handful of pre-configured Sanitizer instances hanging around, ready to use. Something like: `defaultSanitizer.only_string`, `defaultSanitizer.simple_formatting`, and `defaultSanitizer.no_script`. Note that those aren't really new APIs, they are just three pre-configured Sanitizer instances. (Maybe it would be easier to recognize this if we just made them static members on the Sanitizer interface, or something?)


> Have several default settings with a name, [...]

I'm fairly unhappy with this specific proposal. That doesn't allow a developer to (easily) check whether this name is supported. If we want to support pre-configured sanitizers, we should make them available in e.g. a dictionary or as members of an object. (... which is basically what `DefaultSanitzer` was supposed to accomplish.)


> I don't think there's a way to define a sanitizer config that satisfies any complex goal (e.g. no xss) that would still work
after a few years. 

This is true. IMHO, the default(s) should have some reasonably easily explained contract ("no script"; "only plain text") where their behaviour may change to accommodate new browser features (or new attacks). Anyone that wishes to have precise, forward-compatible behaviour can configure their own.

That is:

- Default(s) are just shortcuts for certain configuration options. There can't be "magic" behaviours in the defaults.
- A specific configuration should have identical effects in current and future browsers. (No redefinition of existing options.)
- Default(s) can change in order to maintain their contracts.
- Want ease of use: Use predefined sanitizers. Want full control & forward compatibility: Explicitly define your own config.

**Comment by koto** [comment]
Yes, that works - provided that it's clearly documented that the default sanitizer object(s) behavior might change to keep up the contract as the browser features emerge/get deprecated. Specifically, that it's not guaranteed that for the same input the output will be the same in the next browser release.

That particular property makes it difficult to use the sanitizer in complex apps, as some component further down the line might depend that the sanitizer kept the `<fozen-yogurt>` element, but at some point this might fail, if frozen-yogurt becomes a web feature. The changes are not THAT common though, so maybe it's fine - I just want to make sure we're not painting ourselves in the corner, like we did with [smooshgate](https://developers.google.com/web/updates/2018/03/smooshgate). It is possible a popular library would start depending on a specific sanitizer behavior, practically tying our hands to ever change it. 

Nevertheless, I think as long as there is a way to configure your own sanitizer (to keep frozen-yogurt), more enterprise-y apps would chose that way, even if that means the config needs to change to e.g. keep up with XSS vectors - and simple, or unmaintained applications would get a good-enough experience.

**Comment by otherdaniel** [comment]
I think I get the problem... but it does seem that there are two contradictory requirements: One class of users wants easy-to-use safety, which does imply that the sanitizers will be updated as browsers & attacks progress. The other class of users wants control, and no surprising behavioural changes. Both are right. I think we can give both camps what they want, but only one can have the "default" behaviour.

You're very much right that documenting this properly in the API is key. I tend to underestimate that aspect.

Somewhat tangential, but still related: This is one reason why I'm against a "silent" default: I'd prefer if the user has to make at least _one_ choice, namely _let-the-browser-choose_ or _make-my-own-choice_, and that `(new Sanitizer).sanitize(...)` shouldn't actually work. Make the user pick something, e.g. `Sanitzer.default.sanitize(..)`.

**Comment by mozfreddyb** [comment]
I think we can get away with providing both a evergreen, unstable default that will change in implementation but keep its security guarantees as long as that's clear and obvious.
One could also envision "versioned" defaults that do not change..

**Comment by shhnjk** [comment]
> One could also envision "versioned" defaults that do not change.

I agree with this point. We can do something like `new Sanitizer(latest_default)`, which would be lateast and greatest defense version, where developer also has option to choose `new Sanitizer(default_v1)`, which might be the best sanitizer at a time but will eventually be deprecated with new attacks (so we would give a console error, but still maintain that default).

I also like the idea of different types of defaults. For example, to support same behavior as DOMPurify (i.e. allows _style_ tag) and Clipboard sanitizer (i.e. denies _style_ tag) with same default isn't possible. But I think we should support both, so supporting different types of defaults makes sense to me 😊

**Comment by annevk** [comment]
I feel like we have settled the questions raised in this thread. See also #196.
