### ISSUE TITLE
Semantics of allow vs block vs defaults

### ISSUE THREAD

**Issue by otherdaniel** [WICG/sanitizer-api#33]
@iVanlish has thankfully been looking at implementing this, and we noticed that we've never bothered to define (or agree on) how allow-lists & block-lists & the default config would play together. My current idea would be something like so:

1. For each element in the source fragment, we determine an action `keep` | `block` | `drop`.
2. if `keep`, we keep the element.
3. if `block`, we remove the element and replace it with its children, which we'll process in turn
4. if `drop`, we remove the element and all its children from the tree.

Decision making: If the current element is:

1. in the built-in default drop list: `drop`.
2. in the built-in default block list: `block`.
3. in the config's drop list: `drop`.
4. in the config's block list: `block`.
5. not in the config's allow list and the allow list is non-empty: `block`
6. otherwise: `keep`

---

This is a bit different (& more explicit) than the current proposals:
- Instead of a duality allow/block, this now has three behaviours: allow/block/drop.
- In this definition, drop overrides block, and block overrides allow.
- In this definition, the built-in lists override the config. There is no way to override the built-ins.

I think this definition could be analogously extended for atributes, or namespaced elements.

There are several related issues (#29 #17 #18 #26), but none seem to quite answer this question.

---

Generally, I don't feel super strongly. This is more a request to settle on some specific behaviour than a proposal for a specific one. I'd be particularly interested in feedback from practicioners on whether this matches their needs. @mozfreddyb @shhnjk @koto.

**Comment by iVanlIsh** [comment]
I have a slightly different option of the content 
> * In this definition, the built-in lists override the config. There is no way to override the built-ins.

IMHO, built-ins suppose to be an easy way for people who do not want to bother making costumed configs themselves to start with other than to force people to follow our options of what is sensitive.

So I would suppose:
* Drop overrides block & build-in block & allow;
* Block overrides allow;
* Allow overrides build-in block & build-in drop.

**Comment by otherdaniel** [comment]
_(Feedback delivered to me in private:)_ General skepticism about the allow/block/drop. Allow/block might be just fine for the vast majority of use cases.

**Comment by iVanlIsh** [comment]
Sum up a little bit here:

1. There are three options now for the strategy besides a simple allow or drop choice:
* blocks: may have risks for changing tree structure
* neuter: way to keep the text children
* callbacks: significantly complicate for implementation

2. Allow/drop ( other than allow/block ) might be more practical and would have the vast majority in real life cases.
Reasons down here:
* Block/neuter would very likely to break the stylesheet for a page. Especially modern ones which largely depend on some three-party components and libraries.
* Websites may prefer a drop other than the risk of providing an ugly and broken-looking page to users.
* Callbacks is an option with more freedom for the developers, however, may also be too complicate for large amount of them to use and also need them to take large attention of the potential front-end style problems.

**Comment by shhnjk** [comment]
Maybe we can expose strict parsing more (i.e. `allow/drop`) vs lax parsing mode (i.e. `allow/block`)?

I think this question can be better answered by @cure53, who has experience of making a sanitizer.

**Comment by otherdaniel** [comment]
I'm trying to turn this into spec-suitable algorithms. I think the structure below should work well for the simple cases, and should give us suitable spec-hooks for more complex requirements. (E.g., maybe the built-in defaults won't fit neatly into allow/block lists.) While it's not the best way to implement this, I do think it's a fairly clear way of specifiyting desired behaviour.


**sanitize a document fragment**

1. let m be a map that maps noded to {'keep', 'block', 'drop'}
2. iterate over all nodes
2a call *sanitize a node* and let result be the result value.
2b insert the node and result into m
3. iterate over all nodes.
3a. if m[current] is 'drop', remove the node and all children
3b. if m[current] is 'block', replace the node with its element + text node children.
3c. if m[current] is 'keep' or undefined, do nothing

**sanitize a node**

1. if node is an element: call *sanitize an element*, and return result
2. if node is an attribute: call *sanitize an attribute*, and return result
3. else: do nothing, and return 'keep'

**sanitize an element**

1. set name to the element's constructor name.
2. if name is contained in the built-in default drop-list: return 'drop'.
3. if name is ... (etc., as in starter comment)

**sanitize an attribute**

largely like *sanitize an element*, except with attribute lists. Should probably also receive the parent node's name.

**Comment by cure53** [comment]
> Maybe we can expose strict parsing mode (i.e. `allow/drop`) vs lax parsing mode (i.e. `allow/block`)?
> 
> I think this issue can be better answered by @cure53, who has experience of making a sanitizer.

We have an internal setting which defines if an element can have content or not:
https://github.com/cure53/DOMPurify/blob/main/src/purify.js#L251

If we mess around with those, the different removal behavior might indeed e a cause for XSS rather than preventing it. 

For text content, we usually assume that keeping it is safe:
https://github.com/cure53/DOMPurify/blob/main/src/purify.js#L365

But a user can change that with a global setting if needs be.

**Comment by otherdaniel** [comment]
One very specific thing that came up (again) in (offline) discussion is: Should it be possible to override the built-in block lists?

This has been touched on in several issues, but I don't think we ever reached consensus. That seems like a fairly fundamental decision, so ideally I'd like to get that out of the way...

The way I've tried to define it above is that the built-in block list always apply. (That is, when an element is in the built-in lists, we take that action and do not look at the config.)
An alternative would be to allow the config's allow list to override the built-ins. (e.g. allow_elements = ['script']), or maybe an off-switch similar to DOMPurify's KEEP_CONTENT. 


@iVanlIsh @koto @shhnjk @mozfreddyb  Do people feel strongly one way or another?
@cure53 Why was KEEP_CONTENT introduced? Was there a specific use-case?

**Comment by cure53** [comment]
>  @cure53 Why was KEEP_CONTENT introduced? Was there a specific use-case?

Yes, that was one of the first features requested back then in the olden days: https://github.com/cure53/DOMPurify/issues/15

**Comment by koto** [comment]
I must say though the usecase as outlined in that issue is pretty weak. It does not seem to be about  _sanitizting_ the content, but allowing certain modifications of the tree for non-security reasons (removing `a` or `span` elements, but keeping their texts). This seems quite arbitrary.

**Comment by cure53** [comment]
> I must say though the usecase as outlined in that issue is pretty weak. It does not seem to be about _sanitizting_ the content, but allowing certain modifications of the tree for non-security reasons (removing `a` or `span` elements, but keeping their texts). This seems quite arbitrary.

I thing I disagree, not sure. Maybe I am understanding it the wrong way around - but you appear to be saying this: If anchors are block-listed, we should remove the entire tag, not just the anchoring parts?

You are saying that `one <a>two</a> three` should become `one three` and not `one two three`? Just trying to check if we are on the same page here.

**Comment by koto** [comment]
> If anchors are block-listed, we should remove the entire tag, not just the anchoring parts?

Yes. If a tag is block-listed, all its subtree should be removed, including the text nodes. To my understanding, neither `a` or `span` should be on the default / native block-list - why would they?.

There might be an option to keep the text nodes in place of the specific element tag names, but it should not be the default behavior.

**Comment by cure53** [comment]
> > If anchors are block-listed, we should remove the entire tag, not just the anchoring parts?
> 
> Yes. If a tag is block-listed, all its subtree should be removed, including the text nodes. To my understanding, neither `a` or `span` should be on the default / native block-list - why would they?.
> 
> There might be an option to keep the text nodes in place of the specific element tag names, but it should not be the default behavior.

Cool, then I can wholeheartedly disagree :D Keeping content should be the default, else you will create a sanitizer that will cripple content and throw off developers. I would assume that maybe the GMail team has valuable in-house input on that for you?

**Comment by otherdaniel** [comment]
_".. one of the first features requested ..."_ Hah.

I think we have two issues here, configurability and defaults.

--- 

We seem to have three behaviours when removing an offending element:

1. remove element and all its children,
2. remove element and all element children, but keep the text nodes,
3. remove element, but keep all children (and recurse into children for further sanitization)

So.. KEEP_CONTENT switches (globally) between 1 and 2? What I had proposed above is to allow 1 + 3 to be configured per element (block vs drop). (The use case being something like <script>, where you almost certainly wouldn't want the text content to be displayed, vs removing links, where you would.)

I like the per-element config a bit better, but don't care strongly either way. If KEEP_CONTENT was one of the first feature requests, then I guess that supports the idea that we need at least some configurability for this.

--- 

What I'm trying to figure out right now is orthogonal, namely to what extend we should allow overriding of the default block lists. I.e., can there be a config that would allow <script> elements to stay, or maybe an onclick= event handler.

My initial thought - and the feedback I received - was, why not? If this makes sense for a particular use case, let them do this. But elsewhere, it was argued (I think mainly by Frederik, but not sure) that the sanitizer should uphold some baselevel guarantees in all configs, and we shouldn't make it that easy to shoot oneself in the foot.

**Comment by cure53** [comment]
My high-level argument is this: 

A sanitizer needs to do **two** things: _sanitize_ (duh) and _not cripple content unnecessarily_. The one thing alone is easy. But hard to adopt by real life web applications (web mailers, wikis, RTEs). 

We tackled that with a list of FORBID_CONTENT elements. Can be done with an allow-list too. But note that a overly strict default will produce very unhappy devs and potentially folks fiddling with the config in potentially insecure ways.

**Comment by koto** [comment]
The sanitization bit is about removing the scripting - if we keep to this, there is little impact on changing the appearance or semantics of the text. IOW, KEEP_CONTENT is useful only when the sanitizer is configured to remove more than what directly causes JS execution (and other, related issues like causes DOM clobbering etc). Whether the sanitizer API should be address such usecases is a separate concern (it becames a sanitizer and a kitchen sink of DOM processing), but indeed authors would likely find this useful.

I agree that if the user configures the sanitizer to do non-XSSy additional DOM processing, KEEP_CONTENT issue is surfaced. To answer @otherdaniel's point, I also think it should be per-element, and it should not be able to set it for certain "scripty" elements, if we want to assert the baseline security of the sanitizer.

**Comment by mozfreddyb** [comment]
OK, let me paraphrase what i think we ought to be doing, which is (if I'm not misunderstanding [DOMPurify's code here](https://github.com/cure53/DOMPurify/blob/b552659b914a3849f5eb94b4aa6f4cfe9962bdc3/src/purify.js#L671)):
- keep content generally
- forbid content to be kept for specific elements (DOMPurify uses [this list](https://github.com/cure53/DOMPurify/blob/b552659b914a3849f5eb94b4aa6f4cfe9962bdc3/src/purify.js#L251), Gecko has a [MustPrune function](https://searchfox.org/mozilla-central/source/dom/base/nsTreeSanitizer.cpp#1026) which implements that logic

I don't think we ought to allow the developer to override the default, but I would be open to the developer _adding_ elements to that list.

**Comment by cure53** [comment]
> The sanitization bit is about removing the scripting - if we keep to this, there is little impact on changing the appearance or semantics of the text.

True, if you manage to limit removal to only those critical bits, things might be fine. Meaning, when an `onclick` is found, only remove the attribute and don't touch anything else. But, once the API gets more complex, the problem will come back.

**Comment by iVanlIsh** [comment]
After walking through the discussions, I would like to clarify the behavior for allow lists:
1. Allow list should shows up alone, if not it shouldn't have any effects at all.
2. When allow list shows up, drop or block everything else not in the list.

**Comment by otherdaniel** [comment]
Good news: Zero people are in favour of allowing the baseline guarantees to be configured away. :)

**Comment by iVanlIsh** [comment]
Would `allowAttributes` has the same mechanism or should it be an `extraAllow`? Seems @mozfreddyb mentioned `extraAllow` for attributes in [issue18](https://github.com/WICG/sanitizer-api/issues/18#issuecomment-653423288)

**Comment by otherdaniel** [comment]
I've tried to formalize this discussion in PR #39. Would appreciate if people could take a look, and/or let me know if this needs more discussion.

PR features are:

1, Built-ins are handled first, and thus cannot be overriden.
2, Except dropping an element with all children is handled before built-in element blocking, which should allow us to emulate DOMPurify's KEEP_CONTENT.
  (Assuming that the built-ins e.g. block <script> (but not its content), a user could then add <script> into the drop list, meaning that <script> and all children would be dropped.)
3. I've tried to translate this into spec-like algorithms language. First time, so... please look closely.

(If this finds agreement, I'd try to do a cleanup pass to make sure all references are filled, and would then look at Jun's #31.)
