### ISSUE TITLE
What should the output for creationOptions getter be?

### ISSUE THREAD

**Issue by iVanlIsh** [WICG/sanitizer-api#34]
Break down to following questions:
1. If the user inputs contains invalid configs, should our output remains them? ( Personally consider a NO)
2. Should we format the cases for node/elements name string or not and if so, to upper or lower case? (Personally prefer a Yes but not sure to which case)

WDYT,  @otherdaniel @mozfreddyb @shhnjk @koto.

**Comment by shhnjk** [comment]
Few questions:
1. What is `creationOptions`? I don't see anything in the [spec](https://wicg.github.io/sanitizer-api/).
2. What do you mean by `invalid configs`? For example, is it a config that contains script tag in allow-list, or is it a config that passes random thing in a object? If latter, we will throw an error I suppose.

 >Should we format the cases for node/elements name string or not and if so, to upper or lower case? (Personally prefer a Yes but not sure to which case)

No strong opinions, but cases shouldn't matter IMO.

**Comment by iVanlIsh** [comment]
> 1. What is creationOptions? I don't see anything in the spec.
Sorry for missing in the spec. It is `SanitizerConfig` which users passed in the constructor and can be found here: https://github.com/WICG/sanitizer-api#proposed-api

> 2. What do you mean by invalid configs? For example, is it a config that contains script tag in allow-list, or is it a config that passes random thing in a object? If latter, we will throw an error I suppose.

It is the latter one, and a warning with creation succeed sounds more reasonable for me. For example,
In a configs looks like:`{blockedElements: ["script"], unkownList: ["balabala"]}`, `unknowList` is invalid and we should simply drop it.

In actual logic, the cases are ignored for sure. However, it's uncertain for me whether `creationOptions` getter should return the original input or a normalised object.

**Comment by shhnjk** [comment]
Thank you!

> t is the latter one, and a warning with creation succeed sounds more reasonable for me. For example,
In a configs looks like:{blockedElements: ["script"], unkownList: ["balabala"]}, unknowList is invalid and we should simply drop it.

Sounds good. That might be good for compatibility in case we added new list in v2 and some browser doesn't support v2 yet.

>In actual logic, the cases are ignored for sure. However, it's uncertain for me whether creationOptions getter should return the original input or a normalised object.

I hear you that it complicates things. I think we should normalize the output. And in that case, there might be no reason to allow different cases in the input either 😋

**Comment by otherdaniel** [comment]
I think the two initial questions are related. IMHO, the two options are:

1, `creationOptions` is identical to the options passed into the constructor (including unrecognized options; funny calitalization, etc.)
2, `creationOptions` are the effective options (i.e., normalized from the actual input).

Option 1 is much easier to spec, interop, and testing. Option 2 could be more useful for developers because it allows for some degree of feature detection.

**Comment by otherdaniel** [comment]
Obsolete. (creationOptions were removed a while ago.)
