### ISSUE TITLE
rename to HTMLSanitizer

### ISSUE THREAD

**Issue by nuxodin** [WICG/sanitizer-api#43]
The sanitizer-api in this proposal only targets HTML-syntax.

Maybe sometime we want to habe a e.g. CSSSanitizer:

```js
s = new CSSSanitizer({
    blockUrls: 'extern',
    allowVars: false,
})
```

Or a UnicodeSanitizer:
```js
s = new UnicodeSanitizer({
    blockInvisibleChars: true,
    replaceDiacritics: true,
})
```

**Comment by mozfreddyb** [comment]
The Sanitizer will not only target HTML, but also SVG, MathML at the minimum.
