### ISSUE TITLE
Declarative Shadow DOM should be explicitly considered

### ISSUE THREAD

**Issue by mfreed7** [WICG/sanitizer-api#45]
The [declarative Shadow DOM proposal](https://github.com/mfreed7/declarative-shadow-dom/blob/master/README.md) adds a declarative way to add Shadow DOM to HTML. This opens a [potential sanitizer bypass](https://github.com/mfreed7/declarative-shadow-dom/blob/master/README.md#potential-html-sanitizer-bypass), through a closed shadow root. Given that this proposed sanitizer API lives in the browser, and can therefore "see" even closed shadow roots, it can still provide good filtering. But the current [spec algorithm](https://wicg.github.io/sanitizer-api/#algorithms) does not explicitly traverse into shadow roots. It should likely contain a new step <span>#</span>7, something like:

 7. If node is a shadow host, run the **sanitize a document fragment** algorithm on node's shadow root DocumentFragment.

Or something similar.

**Comment by mozfreddyb** [comment]
thanks for filing! the suggestion makes sense (and I already saw the DOMPurify related discussions on)

**Comment by mozfreddyb** [comment]
We should add text to ensure we recurse into the shadow root. we should be getting most of the rest for free from https://github.com/whatwg/html/pull/9538.
