### ISSUE TITLE
traverse and sanitize within template element?

### ISSUE THREAD

**Issue by mozfreddyb** [WICG/sanitizer-api#58]
Imagine a fragment like
```html
<template><img src="x" onerror="alert(1)"></template>
```

Do we expect the sanitizer to special-case the `<template>` element and traverse into it's `content` attribute?
Firefox currently doesn't support the element, but I'd like to support it and traverse.
From looking at [this testcase](https://github.com/cure53/DOMPurify/blob/98e1ee438798dd11c144c0c5d57648fbfd28fac4/test/fixtures/expect.js#L191) DOMPurify does so too.

From a spec perspective, I think we could check if the element has a `content` attribute of type DocumentFragment (or such), which might also handle Declarative Shadow DOM.

**Comment by otherdaniel** [comment]
I haven't use `<template>`, so I'm not sure if I understand this correctly, but the way I read the docs is that the `.content` attribute mirrors the actual element content, basically like a read-only version of `.innerHTML`. If so, I'd expect no special-casing to be necessary, in that I'd assume Sanitzer would recurse into the children - like for any other element - and `.content` would end up reflecting whatever the surviving content is.

In your example::
  ```<template><img src="x" onerror="alert(1)"></template>  // .content == <img src="x" onerror="alert(1)">```
Post `.sanitize`:
  ```<template><img src="x"></template>  // .content == <img src="x">```

Does DOMPurify acutally special-case `.content`, or is that a fallout of recursing into the children?

**Comment by mozfreddyb** [comment]
Well `content` is not an attribute of the HTML element, but a property of the DOM Node. But I think we agree nonetheless.

**Comment by jonathanKingston** [comment]
Speaking with @mozfreddyb about this;  I think `<template>`, `<slot>` and `data-*` are all of the same ilk, undefined user extensions that can't be guaranteed to be safe in the implementing application.

It's possible with any DOM node to have this risk on injection, but the expectation on these three are clear userland exceptions that a web developer can treat as _here be dragons™_

**Comment by otherdaniel** [comment]
Not sure I follow. 

- `<template>` and `<slot>` seem to contain HTML data. Which is arguably exactly what an HTML sanitizer would know how to deal with.

- `data-*` just appears to be text strings that are easily accessible by CSS or custom elements, but fundamentally the same as any other attribute of text content.

Am I still something?

It does strike me that they should be default-blocked. But blocking them in a non-overridable fashion seems a bit much, and in that case we need to define how to handle them.

**Comment by jonathanKingston** [comment]
> It does strike me that they should be default-blocked.

That's what I'm striving for, that and they are quite different to `<p>` if we are talking about defaults that might be permitted. (Freddy and I spoke about having some sane defaults that developers could extend from)

The example of risk for data-* being something like this from Bootstrap:

```
<button type="button" class="btn btn-secondary" data-toggle="tooltip" data-html="true" title="<em>Tooltip</em> <u>with</u> <b>HTML</b>">
  Tooltip with HTML
</button>
```

**Comment by otherdaniel** [comment]
That makes sense, and the present proposals for default handling cover this.

We're now splitting this between default (what you get with no config) and baseline (what you always get; non-overridable). That way, we can be a lot more aggressive about what to put into the defaults. Present proposal is to have allow-lists for both elements and attributes. Not sure if `<template>` and `<slot>` are in the default allow-list; I'll check, and if they are, I'll gladly remove them.

So if someone does want e.g. `data-blabla`, they'd have to explicitly allow it in their config.

**Comment by mozfreddyb** [comment]
Yeah, rethinking, I assume we want slot, template, data- to be allowable, but not default-allowed.
Not sure if that means we need to traverse into template implicitly or suggest folks to do it manually now :shrug:
