### ISSUE TITLE
Consider respecting baseline settings for all sanitizers

### ISSUE THREAD

**Issue by koto** [WICG/sanitizer-api#59]
Problem: Some applications are more sensitive w.r.t to what elements/attributes should the sanitizer output. 

For example, some applications are built on frameworks that recognize custom XSS sinks (i.e. that have [script gadgets](https://github.com/google/security-research-pocs/tree/master/script-gadgets)), or e.g. wish that all images were stripped, or wish that iframes are not present, or only some tags related to text formatting are supported.

The sanitizer API solves that problem via sanitizer config, that may be arbitrarily strict, but it doesn't solve the following: How to guarantee that _all_ sanitizers adhere to those rules? E.g. How to prevent arbitrary 3rd party dependency, that uses Sanitizer, from inserting DOM nodes violating my custom restrictions? 

There's a couple of ways how this problem could be addressed. For example, some integration with Trusted Types which already deals with guarding certain sinks could be possible (#55 explores that). But there are also some ways this could be addressed without TT:

### A. Event that can modify / reject config at creation time

Similar to https://github.com/w3c/webappsec-trusted-types/issues/270, there could be an event dispatched that allows for inspecting the configuration of a sanitizer when it's created. 

```javascript
Sanitizer.addEventListener("beforecreate", (event) => {
  try {
    event.config = massage(event.config);
  } catch (e) {
    console.error("config so bad I can't recover");
    e.preventDefault(); // Sanitizer creation throws.
  }
});
```

### B. Baseline configuration

```javascript
Sanitizer.setBaseline(baselineCfg);
```
This would assert that restictions in the baseline is respected for every Sanitizer construction afterwards.
The effective "merging" of configurations TBD, but it might be some form of: `effectiveCfg = Object.assign(givenCfg, baselineCfg)` (it gets a bit more complex with allowlists / blocklists).

There are also ways to implement that in userland code:

### C. Create a Proxy early (userland)

```javascript
Sanitizer = new Proxy(Sanitizer, {
  construct(target, args) {
    console.assert(respectMyRules(args), "invalid sanitizer config");
    // or change the rules to respect the application-specific baseline.
    return new target(...args);
  }
});

const s = new Sanitizer(configRespectingTheRules); // yay!
```
### D. Remove the Sanitizer (userland)
```javascript
// Run me early
export const myOneTrueSanitizer = new Sanitizer(customXssCfg);
delete Sanitizer; // 😱
```

// cc @mikewest @otherdaniel @shhnjk @mozfreddyb

**Comment by otherdaniel** [comment]
I like this idea, both as a problem statement as well sketching out solutions. Without having thought about this too deeply, I wonder if we could define a "configuration merge", where the allow-lists are joined by set-intersection and block-lists by set-union. That'd make it easy to support a configurable baseline.

---

An (admittedly somewhat un-web-ish) alternative might be to rely on "parent sanitizers", where you can't create any sanitizers on their own, but only from another existing instance, with the default being auto-created for you. E.g., there'd be a `globalThis.defaultSanitizer` available, and each Sanitizer instances has a `.create(config)` method (instead of an exposed Sanitizer constructor). That way, developers always have to pick a base config. And to lock it down, one could replace the global defaultSanitizer with one own's instance.

**Comment by mozfreddyb** [comment]
I'm not sure if this is true, but it looks that you could approach this similar to how you do it with TrustedTypes?
With TT you only have to audit the policies.
With the Sanitizer, you have to audit the constructors.

If we combine the two concepts in the way *I* would currently prefer it, you might limit the Sanitizer constructor to something that can only happen within a TT policy and you got to do no extra work in terms of auditing..

**Comment by mozfreddyb** [comment]
To be fair, if this sounds too dismissive. I'm not overly sold the on the issue that the Sanitizer needs to be able to police third-party code (e.g., libraries), but maybe this is a real problems that developers are facing?

If possible, I'd like to table this until discussion until we got The Basic Thing (defaults, user configuration, sanitizing algorithm) figured out.

**Comment by koto** [comment]
> If we combine the two concepts in the way I would currently prefer it, you might limit the Sanitizer constructor to something that can only happen within a TT policy

Do you propose to built this restriction into the API (i.e. `new Sanitizer` should throw if there are some runtime restrictions set up), or to solve that problem elsewhere (e.g. by statically analyzing the code of the application to make sure the Sanitizer is never constructed outside of a TT policy)?

If the former is true, then the consequence is that the API becomes _less_ portable, as there would be two mutually exclusive ways to instantiate the sanitizer. One for enviroments without the restrictions (`new Sanitizer`) and one without (some wrapping e.g. via TT). If one works, the other one does not, and that introduces problems for both 1st and 3rd party code. 

If we consider the Sanitizer API risky, then we should find a way to control its usage, but in a way that's portable. Coupling with TT unfortunately isn't, so I don't think it's a right solution to this issue.

For the sake of completeness, let me put forward:

## E. Guard Sanitizer instance creation by name.

Similar to `trusted-types` CSP directive, allow the authors to restrict Sanitizer creation by requiring a sanitizer name:

```javascript
new Sanitizer('foo', config) // name could also be part of config
```

By default, the name is ignored. A CSP directive could limit which names are allowed, e.g.

```javascript
// Content-Security-Policy: sanitizer foo bar 'allow-duplicates';

new Sanitizer('foo', {}) // OK
new Sanitizer('foo', {}) // OK
new Sanitizer('baz', {}) // CSP Violation + Type error.
```

I like this as it integrates well with CSP report-only logic, decouples Sanitizer from TT (it's a different problem space, though both APIs are guardable), and provides an easy extension point for sanitization-by-default with `new Sanitizer('default', {})` 

> I'm not overly sold the on the issue that the Sanitizer needs to be able to police third-party code

Given that HTML sanitization is not an easy task, and bugs in sanitizer logic do lead to XSSes, I think I disagree here. We already limit powerful APIs to secure contexts to protect against attackers on the wire, but fail to recognize that the largest security risk comes from bugs and mishandling those APIs in your dependencies. Adding platform guards to control which code in your application is allowed to do security-sensitive operations is both easy and necessary to secure complex applications. Only giving global access to the API and hoping it won't be misused is leaving the most difficult task to the authors. 

> I'd like to table this discussion

That's fair, but some of the options outlined can limit what "the basic thing" is. For example, we know for sure that Saintizer can never allow for standard XSS, certain config options might make it impossible for option B etc.

**Comment by koto** [comment]
I've created some prototype for options C and D and E, built in a way that make it possible to guard any function constructor, not just `Sanitizer`: https://codesandbox.io/s/restless-http-z4t8c?file=/src/index.js
