### ISSUE TITLE
Change default branch name to "main"

### ISSUE THREAD

**Issue by mozfreddyb** [WICG/sanitizer-api#66]
I plan to change the default branch name to `main`, my understanding is that GitHub's support should cause little interruptions for PRs that are already inflight, but will require local branches that are checked out on `master` to switch.
I must admit that my knowledge of unintended side-effects are a bit limited, so don't take my word for it ;-)

I don't have a specific date in mind, but noticed that official-W3C repos have already switched.

@otherdaniel, @iVanlIsh Please let me know if there's anything in progress which would be interrupted by this, otherwise I will make the change at the end of this week.

**Comment by otherdaniel** [comment]
This may need adapting: https://github.com/WICG/sanitizer-api/blob/master/deploy.sh#L9

Otherwise lgtm.

**Comment by otherdaniel** [comment]
I assume these instructions largely summarize the actions on the client: https://lists.w3.org/Archives/Public/public-web-perf/2021Feb/0003.html

**Comment by mozfreddyb** [comment]
Well, apparently I didn't get to it. FWIW, I'll prioritize reviews before I touch this, hoping not to break too many PRs in this way.

**Comment by otherdaniel** [comment]
I think this has been completed.
