### ISSUE TITLE
How to identify namespaces / SVG + MathML

### ISSUE THREAD

**Issue by otherdaniel** [WICG/sanitizer-api#72]
The current spec uses a tag's local name, meaning it cannot distinguish between SVG, MathML, and HTML element names. Clearly, that won't do long-term.

**Comment by otherdaniel** [comment]
Honestly, I have no idea what a good answer is here, Would appreciate feedback. Several proposals below. IMHO, they are all viable, but with different aesthetics.


In an XML-centric world -- which is where namespaces were invented -- this is easy: QNames everywhere => problem solved. It's just that HTML didn't go the XML-centric route, so I'm not sure whether that should be our answer here.


I think there's two questions: Whether to consider fixed vs arbitrary namespaces, and syntax.

Should we consider arbitrary namespaces, or only the browser-supported ones? That is, should a Sanitizer config be able to specify `<foobar>` from the `http://example.org/ns/bla` namespace, or is it sufficient (and certainly easier) to map elements - for Sanitizer purposes - into the triple choice [`HTML`|`SVG`|`MathML`], or maybe a quadruple choice with `other`?

There'd be a number of ways to represent this (depending a bit on the previous question):

- separate lists: `{ allow_elements: [...], allow_svg_elements: [...], ...}`
- unified lists with 'known' prefixes: `{ allow_elements: [ "div", "svg:bla", "math:bla" ] }`
- unified lists with qnames: `{ allow_elements: [ "http://www.w3.org/2000/svg:script" ] }`
- nested structure: `{ allow_elements: { "http://www.w3.org/2000/svg:script" : [ "foo" ] } }`

**Comment by mozfreddyb** [comment]
A few ill-thought out ideas while I'm already stepping away from my desk.
Do we need the full namespace or can we shorten to html:, svg:, mathml:?

I'm hopeful we don't have to solve this for arbitrary namespaces but hardcode a couple of them? I don't expect lots of new namespaces with their own parsing rules to creep up any minute (I might be wrong!)

**Comment by otherdaniel** [comment]
> Do we need the full namespace or can we shorten to html:, svg:, mathml:?

We can absolutely do that, and IMHO it'd be simpler.

I would like to be sure that we aren't overlooking a use case for arbitrary namespaces, though. If we don't strongly care about that - which I don't - then I think we have a pretty easy solution.

**Comment by securityMB** [comment]
Can we make the namespaces implicit? For instance: `<textarea>` exists only in HTML, so it should be only allowed within HTML namespace, while `<mtext>` is valid in MathML so it should be discarded in other namespaces?

**Comment by otherdaniel** [comment]
> Can we make the namespaces implicit?

What about `<a>`, which can be either in HTML namespace (`HTMLAnchorElement`) or SVG namespace (`SVGAElement`)?
(`<image>` is svg only, but has weird parsing rules in HTML.)

**Comment by securityMB** [comment]
I'd assume that if element is valid for more than one namespace, it would be valid in all of them. So simple `<a>` would make it allowable in both SVG and HTML.

I'm aware of five tags that are valid in two namespaces: `<title>`, `<style>`, `<font>`,  `<a>`, `<script>`.

**Comment by otherdaniel** [comment]
> I'd assume that if element is valid for more than one namespace, it would be valid in all of them. So simple <a> would make it allowable in both SVG and HTML.

I like this. It seems both simple and effective. Also, amusingly, it means that the spec "by accident" already mostly does the right thing, since this would mean we act on the tag names only, and largely ignore namespaces.

Disadvantages, for completeness sake:
- In several places, the spec references elements by their interface (e.g `HTMLAnchorElement`) instead of their tag name. We should either rewrite that, or have be to extra careful that we're always covering the different variants, where they exists.
- I find it a bit clumsy from a theoretical perspective, since this would e.g. make it impossible to allow HTML's `<a>`, but disallow SVG's `<a>`. That said, I note that simplicity is a major project goal, while "theoretical non-clumsiness" isn't. (Maybe one could have an additional top-level boolean for SVG and MathML on/off; but interpret the allow/block lists only based on the tag name.)

> [edit]: The reasoning for that is from my experience developers mainly are aware of tag names, not the namespaces shenanigans. So that should match their expectations.

I very much suspect this is correct.

**Comment by securityMB** [comment]
> * I find it a bit clumsy from a theoretical perspective, since this would e.g. make it impossible to allow HTML's `<a>`, but disallow SVG's `<a>`. That said, I note that simplicity is a major project goal, while "theoretical non-clumsiness" isn't. (Maybe one could have an additional top-level boolean for SVG and MathML on/off; but interpret the allow/block lists only based on the tag name.)

Maybe we can have a bit both of both worlds:
* if developer specifies `a` in allowlist, then we assume `a` tags in all namespaces it's valid (SVG and HTML),
* if developer specifies `svg:a` or `html:a` in allowlist then only `a` in SVG and HTML respectively would be allowed.

**Comment by otherdaniel** [comment]
It's been a while. The current status is:

- elements support SVG + MathML, using fixed `"svg:"` and `"math:"` prefixes.
- attributes supports a fixed set of namespaced attributes, taken [directly from the HTML spec](https://html.spec.whatwg.org/multipage/syntax.html#attributes-2).

This purposely limits Sanitizer to support the exact same namespaced content as HTML does.

I think this resolves the issue; but I'll wait for a bit with closing it in case anyone disagrees.

**Comment by zcorpan** [comment]
The spec isn't very clear about how the attribute match list namespace mapping works, imo. Is the namespace mapping always applied? Or only when the element is "svg:*" or "mathml:*"?

**Comment by otherdaniel** [comment]
> The spec isn't very clear about how the attribute match list namespace mapping works, imo. Is the namespace mapping always applied? Or only when the element is "svg:*" or "math:*"?

Thanks for the feedback!

The intent is:
- There is a finite list of (currently) 11 namespaced attributes, defined in [HTML](https://html.spec.whatwg.org/multipage/syntax.html#attributes-2). We'll recognize exactly those, in exactly the syntax of the attribute table in HTML, and nothing else.
- It doesn't matter what element they belong to.

I'll try to clarify the wording.

(My own problem when trying to spec that was that, knowing how namespaces work in XML, I found the HTML adoption of this concept fairly strange. But I believe our current solution faithfully matches what HTML does.)

**Comment by zcorpan** [comment]
OK. Note that the HTML syntax only supports these namespaced attributes on foreign elements.

**Comment by otherdaniel** [comment]
> OK. Note that the HTML syntax only supports these namespaced attributes on foreign elements.

Good point, I had overlooked that. This is presently mis-specified in Sanitizer.
