### ISSUE TITLE
Sanitizer config introspection.

### ISSUE THREAD

**Issue by otherdaniel** [WICG/sanitizer-api#77]
This came up during TAG review (w3ctag/design-reviews#619): _"Exposing the config on Sanitizer instances (possibly read-only) could provide an easy solution for this use case. Exposing the default config as a static property on Sanitizer might be helpful too."_ 

- A similar thought came up in #64.
- A similar mechanism existed in very early versions of our (Chrome's) implementation (`.createOptions` property)
- TAG considers whether this should be elevated to a design principle: w3ctag/design-principles#300

I think the specific question raised by TAG (how to block a specific element) can be resolved elsehow (namely by `blockElements:`), but I think the general question remains: Should we support query-ing any sanitizer instance's config, and/or the default config, with the primary use case being building a derived configuration.

**Comment by iVanlIsh** [comment]
I would vote for we should since it looks like a fairly convenient feature for the developers.

**Comment by mozfreddyb** [comment]
Yes! I think it would be really useful to expose the defaults (in the Sanitizer global) _and_ an instance's config (through an attribute).

**Comment by otherdaniel** [comment]
Good. I've started spec-ing something; will send a PR soon-ish.

_"through an attribute"_: WebIDL spec says attributes can't be dictinonary-valued. I don't understand why; but I've picked parameter-less methods to be safe. (Am super happy to change in case I misunderstood this.)

**Comment by otherdaniel** [comment]
Resolved (#80).
