### ISSUE TITLE
Limitations in the protection against arbitrary code execution

### ISSUE THREAD

**Issue by benbucksch** [WICG/sanitizer-api#89]
I've invented and implemented the first version of the sanitizer in Mozilla, in 2002.

I had created the sanitizer as an *additional* (!) protection on top of `<browser type="content">`, to isolate malicious HTML from privileged JS with system principal. It is explicitly *not* capable to be the **only** protection from malicious HTML in privileged JS contexts that can run arbitrary code on the local machine, for example in Electron. The attack surface of HTML is just too large to be 100% sure to cover everything.

Rather, it was intended as additional protection for cases where the browser has a security hole. Browsers are not secure enough, given that they have several security holes every single week of the year. In some contexts, this is not acceptable. That's what the sanitizer was for, to given protection where the browser alone is too insecure.

It's one thing to use a sanitizer as XSS protection. Worst case, your account on that site gets hacked. It's a completely different thing as protection against arbitrary code execution. Worst case, all your accounts get hacked, all passwords leak, all your documents leak, and your computer is used to attack the rest of the local network.

It seems you are aware that the protection is not complete. The document has limitations like "browser has a *fairly* good idea", "the library... will be updated ... as bugs or new attack vectors are found", which is fair. The entire problem is that the browser has too many security bugs, and the sanitizer was intended as additional protection, exactly to stop them and put an end to the endless browser bugs.

And it did. The sanitizer together with the iframe protection only *ever* had 2-3 security bugs that I know about, within ~10 years. This is in contrast with the browser, which has 2-3 security bugs *per week*. This is unacceptable in many contexts.

My advise: The sanitizer is great for low security contexts, against low risk XSS, e.g. for user comments on a blog. For higher security contexts, e.g. apps with system rights with arbitrary code execution rights on the local machine, I advise to explicitly state that this sanitizer is a good complement, but alone is not sufficient. Additional protections are needed.

I don't want the sanitizer to be the cause for the next broken pipeline, poisioned tap water, or shut down hospital.

**Comment by mozfreddyb** [comment]
I think we agree that the sanitizer as an XSS protection has its limitations and we already cover that in https://wicg.github.io/sanitizer-api/#security-considerations, we don't currently advertise the sanitizer as a one-size-fits-all protection for all use cases or levels of privilege.

Please be more precise if you have a specific suggestion for changing the spec text though.

**Comment by benbucksch** [comment]
Sure, I'll make a Pull Request.
