### ISSUE TITLE
What about DOM clobbering?

### ISSUE THREAD

**Issue by mozfreddyb** [WICG/sanitizer-api#9]
Do we want to include heuristics as to whether disallow e.g., id, name attributes or disallow generally?

**Comment by shhnjk** [comment]
This could be another version of default I think 😊

**Comment by mozfreddyb** [comment]
We've discussed this in #65 and I suggest developers disallow `id` and `name` if they want to prevent clobbering.

**Comment by mozfreddyb** [comment]
(Happy to revisit in the future btw :))
